import { describe, expect, it } from 'vitest';
import {
  defaultLocale,
  locales,
  nativeNames,
  type Locale,
} from '@/i18n/locales';
import de from '@/messages/de.json';
import en from '@/messages/en.json';
import fr from '@/messages/fr.json';
import it_ from '@/messages/it.json';
import ro from '@/messages/ro.json';
import {
  renderNotFoundHtml,
  type NotFoundBlock,
  type NotFoundLink,
} from './not-found-html';

// lib/not-found-html — THE DOCUMENT-SHAPE SUITE for out/404.html, the dispatcher a
// static host serves for every unknown URL. tools/generate-404.ts assembles it
// from this module's builders, the five message files and src/i18n/href.ts;
// this file asserts that what comes out is a real HTML document whose no-JS
// fallback is usable on its own, by handing the text to the SAME parser a
// browser uses.
//
// ── WHY A PARSER AND NOT A STRING MATCH. The builders return text, so every
// claim below could be spelled as `toContain`, and the unit suite
// (tests/unit/not-found-404.test.ts) does exactly that for the pieces. What a
// string match cannot answer is the question this document's accessibility
// rests on: "does the parsed DOCUMENT have exactly one h1, and is every
// language's text inside an element declaring that language?" DOMParser answers
// it the way a screen reader would — which is why this suite lives in the
// components project (real Chromium, §13) rather than beside its logic twin in
// node.
//
// ── THE STRINGS COME FROM src/messages/*.json (§17.4), never from fixtures: a
// renamed key fails HERE as well as in the parity gate, instead of shipping a
// document that says "common.notFound.title" in five languages.

const MESSAGES: Record<
  Locale,
  { common: { notFound: { title: string; message: string } } }
> = { ro, en, de, fr, it: it_ };

/** Blocks and links in MANIFEST order (ro first) — the same order the tool
 *  builds them in, so this suite photographs the shipped sequence. */
const BLOCKS: readonly NotFoundBlock[] = locales.map((locale) => ({
  locale,
  title: MESSAGES[locale].common.notFound.title,
  message: MESSAGES[locale].common.notFound.message,
}));

const LINKS: readonly NotFoundLink[] = locales.map((locale) => ({
  locale,
  href: `/${locale}/404/`,
  name: nativeNames[locale],
}));

const STYLESHEETS = ['/_next/static/chunks/fixture.css'];

const document_ = new DOMParser().parseFromString(
  renderNotFoundHtml({
    lang: defaultLocale,
    htmlClassName: 'serif-variable mono-variable',
    title: `404: ${ro.common.notFound.title} — ${ro.common.siteName}`,
    stylesheets: STYLESHEETS,
    basePath: '',
    cookieName: 'NEXT_LOCALE',
    defaultLocale,
    blocks: BLOCKS,
    links: LINKS,
    generatedNote: 'GENERATED by tools/generate-404.ts',
  }),
  'text/html',
);

describe('the generated 404 dispatcher', () => {
  it('declares the default locale on the root, with the shell’s font classes', () => {
    // The failure this replaces is Next's own default 404.html, which ships a
    // bare <html> — no lang at all on a document that speaks five languages.
    expect(document_.documentElement.getAttribute('lang')).toBe(defaultLocale);
    expect(document_.documentElement.className).toBe(
      'serif-variable mono-variable',
    );
  });

  it('has exactly one h1, whose lines are the five titles', () => {
    const headings = document_.querySelectorAll('h1');
    expect(headings).toHaveLength(1);

    const spans = [...headings[0].querySelectorAll('span')];
    expect(spans).toHaveLength(locales.length);
    spans.forEach((span, index) => {
      const block = BLOCKS[index];
      // SC 3.1.2 Language of Parts: without its own `lang`, "Diese Seite
      // existiert nicht" is pronounced by the document's Romanian voice.
      expect(span.getAttribute('lang')).toBe(block.locale);
      expect(span.textContent).toBe(block.title);
    });
  });

  it('has one justified paragraph per language, each declaring its own', () => {
    const paragraphs = [...document_.querySelectorAll('main p')];
    expect(paragraphs).toHaveLength(locales.length);
    paragraphs.forEach((paragraph, index) => {
      const block = BLOCKS[index];
      expect(paragraph.getAttribute('lang')).toBe(block.locale);
      expect(paragraph.textContent).toBe(block.message);
      // The owner's 2026-09-07 reversal ("f*ck justify keep centered",
      // superseding 2026-09-06's justify): centred body text, here as on the
      // routed shell page — a PER-ELEMENT override, never a wrapper's blanket
      // (§15.15 b, PR #70 canon).
      expect(paragraph.classList.contains('text-center')).toBe(true);
    });
  });

  it('offers a labelled way into each locale’s real page', () => {
    const list = document_.querySelector('main ul');
    // `role="list"` is redundant in the spec and load-bearing in WebKit:
    // Tailwind's preflight sets `list-style: none`, and Safari then drops list
    // semantics outside a <nav> (the repo's own eslint carve-out says so).
    expect(list?.getAttribute('role')).toBe('list');

    const anchors = [...document_.querySelectorAll('main li a')];
    expect(anchors).toHaveLength(locales.length);
    anchors.forEach((anchor, index) => {
      const link = LINKS[index];
      expect(anchor.getAttribute('href')).toBe(link.href);
      // Each name is IN its own language, so it carries its own lang — and
      // hreflang, the destination's (same code both times). The root stub's
      // link list, exactly.
      expect(anchor.getAttribute('lang')).toBe(link.locale);
      expect(anchor.getAttribute('hreflang')).toBe(link.locale);
      expect(anchor.textContent).toBe(link.name);
    });
  });

  it('puts every part inside the one <main> landmark', () => {
    const mains = document_.querySelectorAll('main');
    expect(mains).toHaveLength(1);
    expect(mains[0].querySelectorAll('h1, p, ul')).toHaveLength(
      1 + locales.length + 1,
    );
  });

  it('is unconditionally noindex', () => {
    const robots = document_.querySelector('meta[name="robots"]');
    expect(robots?.getAttribute('content')).toBe('noindex');
  });

  it('links every stylesheet the build handed it', () => {
    const hrefs = [
      ...document_.querySelectorAll('head link[rel="stylesheet"]'),
    ].map((link) => link.getAttribute('href'));
    expect(hrefs).toEqual(STYLESHEETS);
  });

  it('runs one script, last in the head, that forwards to a real destination', () => {
    const head = [...(document_.head?.children ?? [])];
    const scripts = head.filter((node) => node.tagName === 'SCRIPT');
    expect(scripts).toHaveLength(1);
    expect(head.indexOf(scripts[0])).toBe(head.length - 1);
    expect(document_.body.querySelectorAll('script')).toHaveLength(0);

    // The forward targets are the SAME hrefs the visible list offers, so a
    // visitor with JavaScript and one without end up in the same five places.
    const text = scripts[0].textContent ?? '';
    expect(text).toContain('location.replace');
    for (const link of LINKS) expect(text).toContain(link.href);
  });

  it('carries no style block any more', () => {
    // The CSS-hiding mechanism died with the dispatcher rework (owner
    // 2026-09-06): nothing is hidden here, because the document is left in one
    // frame at most and the real page is a routed shell page.
    expect(document_.querySelectorAll('style')).toHaveLength(0);
  });
});
