import { createRef } from 'react';
import { render, screen } from '@testing-library/react';
import { describe, expect, expectTypeOf, it } from 'vitest';
import type { Rating } from '@/lib/rating/rating';
import {
  ReviewCard,
  type ReviewCardProps,
  type ReviewTone,
} from './ReviewCard';
import source from './ReviewCard.tsx?raw';

// sections/ReviewCard — the interaction suite. Role-based queries wherever a
// role exists (§9, §13): a passing test doubles as proof of accessible markup,
// and here that is half the component's job — the card is reachable as an
// `article` NAMED BY ITS OWN TITLE because a real <h3> and a real
// aria-labelledby pair say so, never because something wears a size.
//
// ── WHAT THIS FILE IS ACTUALLY FOR: THE MORPH (ledger D1a, the owner's
// pitfall). The deck marks its current slide by handing this card a different
// `tone`, and the invariant is that NOTHING ELSE moves — the same DOM node,
// the same photograph, the same words. That is exactly the class of regression
// a screenshot cannot catch (both pictures look right; the node was replaced
// in between), so it is pinned here, in both directions.
//
// ── HARNESS NOTE — there is NO NextIntlClientProvider in this file, and that
// absence is itself an assertion (the Wordmark/SectionHeading precedent).
// next-intl's hooks throw without one, so a green render proves what the
// contract states: this section calls no t() and owns zero message keys. Every
// string below is a FIXTURE the band would have translated — Romanian with
// diacritics (§15.7), factual, no superlatives or result guarantees (CMSR, in
// force since 2025-07-01). RO_ALL carries all seven Romanian marks, so a
// broken encoding path fails here rather than in front of a patient.
//
// ── WHAT THE PICTURE FACE DOES IN THIS RUNNER, and why every picture
// assertion below is SYNCHRONOUS (the rule ui/Avatar.test.tsx records in
// full): the optimized URLs the loader emits do not exist here — that folder
// is generated by `npm run build` and gitignored — so every <img> 404s and a
// REAL error event arrives at a macrotask boundary, which trips ui/Avatar's
// own picture→letters fallback. Render, read, re-render, assert, with no
// `await` in between: the morph is tested as a mechanism, not as a race.
//
// ── STYLES ARE NOT LOADED in this project (tests/setup/components.ts imports
// no stylesheet), so computed values would read back as browser defaults: the
// utility TOKENS are the contract here, the convention every component test in
// this repo follows. Two things therefore live one tier up, in
// ReviewCard.stories.tsx, where the real sheet is present: the generated quote
// marks (`content: open-quote` resolving per the document's language) and the
// wrapping/hyphenation of a German review inside the card's padding.

const REVIEW = {
  id: 'andreea-popescu',
  initials: 'AP',
  rating: 4.5,
  ratingLabel: '4,5 din 5 stele',
  title: 'Explicații pe îndelete',
  body: 'Am venit pentru o consultație și mi s-au explicat pașii tratamentului. Ședințele au început la ora programată.',
  name: 'Andreea Popescu',
  procedure: 'Consultație',
} as const;

/** All seven Romanian marks — Ș ș Ț ț ă â î — in one line of body copy. */
const RO_ALL = 'Ședințe în Târgoviște — găsiți Țepeș';

// The committed demo photograph, reused rather than a reviewer's face: real
// reviewer pictures are the owner's to supply (§11). `alt: ''` is what the
// deck passes and is a decision, not a hole — the disc repeats a name the
// caption already prints (ui/Avatar's D-A1).
const PICTURE = { src: '/images/demo/hero-calm.jpg', alt: '' } as const;

// THE two tone rows and the two atom recipes, written OUT rather than imported
// (the ui/Eyebrow RECIPE convention): a silent edit to ui/Card's lookup or to
// ui/Heading's scale must fail HERE, against an independent copy, instead of
// following the component it is supposed to be checking.
// Only the tokens that DIFFER between the rows plus the shared radius — never
// ui/Card's whole class string: the atom's geometry is its own file's pin (and
// its single-spelling fence, tests/unit/card-single-spelling.test.ts, would
// count a contiguous copy of it here as a second spelling).
// Both rows read ONE colour, `--card-tint` (Card.tsx's ONE TINT paragraph,
// owner 2026-09-12): the idle frame IS the selected ground.
const FRAMED = [
  'border-[3px]',
  'border-(--card-tint)',
  'bg-surface',
  'p-[calc(1.5rem-2px)]',
];
const EMPHASIZED = [
  'border',
  'border-(--card-tint)',
  'supports-[color:color-mix(in_lab,red,red)]:bg-(--card-tint)',
  'p-6',
];
const RADIUS = 'rounded-md';
const TITLE_STEP = ['font-display', 'text-xl', 'text-ink-strong'];
const EYEBROW_RECIPE =
  'font-mono text-sm font-medium tracking-widest text-ink-muted uppercase';
const BODY_RECIPE = [
  'text-base',
  'text-ink-muted',
  'before:content-[open-quote]',
  'after:content-[close-quote]',
];
const FIGCAPTION = 'flex flex-col gap-0.5 border-t border-line-subtle pt-3';
// THE COMPENSATION SPACE (owner 2026-09-12): the figure takes the card's
// slack and the blockquote takes the figure's, so the credential under it sits
// at the same height on every card of a deck whose cards share one height.
const FIGURE = 'flex flex-1 flex-col gap-3';
const BLOCKQUOTE = 'flex-1';

// Read through the ATTRIBUTE, not through `.className`: the sweeps below walk
// every descendant, and ui/StarRating's five slots contain <svg> elements,
// whose `className` is an SVGAnimatedString rather than a string (measured
// here — it throws `split is not a function`). The attribute is the same bytes
// on both kinds of element.
const tokensOf = (element: Element): string[] =>
  (element.getAttribute('class') ?? '').split(/\s+/).filter(Boolean);

/**
 * The section's source with its PROSE removed, which is what the zero-island
 * guards at the bottom run against (mechanism copied from Wordmark.test.tsx,
 * where its reasoning is written out in full). Without it those guards police
 * the file's own documentation: the header discusses `'use client'`, `t()` and
 * the hooks it does NOT have, by name. Known limit, same as there: it strips
 * block comments and whole-line `//` comments, not a `//` trailing real code —
 * a shape this file does not contain, and one that is visible in review.
 */
const stripComments = (code: string): string =>
  code.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^[ \t]*\/\/.*$/gm, '');

const CODE = stripComments(source);

describe('ReviewCard — THE MORPH: tone changes, the card does not (D1a)', () => {
  it('keeps the SAME article node, photograph and words across framed → emphasized → framed', () => {
    // Fully synchronous by design (see the header): the picture is read
    // before the runner's 404 can fire ui/Avatar's fallback, so what is
    // compared is the same <img> element the deck would keep in production.
    const { rerender } = render(
      <ReviewCard {...REVIEW} picture={PICTURE} tone="framed" />,
    );

    const article = screen.getByRole('article', { name: REVIEW.title });
    const picture = article.querySelector('img') as HTMLImageElement;
    const words = article.textContent;
    expect(picture.getAttribute('src')).toBeTruthy();
    for (const token of [...FRAMED, RADIUS]) {
      expect(tokensOf(article)).toContain(token);
    }

    rerender(<ReviewCard {...REVIEW} picture={PICTURE} tone="emphasized" />);

    // ONE element through the whole swap. A re-created node would keep every
    // class assertion green while the deck's crossfade had nothing to
    // interpolate from — and would drop a focused element inside it.
    expect(screen.getByRole('article', { name: REVIEW.title })).toBe(article);
    expect(article.querySelector('img')).toBe(picture);
    expect(article.textContent).toBe(words);
    for (const token of [...EMPHASIZED, RADIUS]) {
      expect(tokensOf(article)).toContain(token);
    }
    // …and the idle row is gone, not merely joined: two `p-*` utilities on one
    // element would put the inset at the mercy of stylesheet order.
    expect(tokensOf(article)).not.toContain('border-[3px]');
    expect(tokensOf(article)).not.toContain('p-[calc(1.5rem-2px)]');
    // `bg-surface` is now the emphasized row's opaque BASE too — the tell is the tint token.
    expect(tokensOf(article)).toContain(
      'supports-[color:color-mix(in_lab,red,red)]:bg-(--card-tint)',
    );

    rerender(<ReviewCard {...REVIEW} picture={PICTURE} tone="framed" />);

    expect(screen.getByRole('article', { name: REVIEW.title })).toBe(article);
    expect(article.querySelector('img')).toBe(picture);
    expect(article.textContent).toBe(words);
    for (const token of FRAMED) expect(tokensOf(article)).toContain(token);
    expect(tokensOf(article)).not.toContain(
      'supports-[color:color-mix(in_lab,red,red)]:bg-(--card-tint)',
    );
    expect(tokensOf(article)).not.toContain('p-6');
  });

  it('holds the same invariant on the letters face — no picture, same node', () => {
    // The other half of the deck's population, and the one that cannot be
    // disturbed by an image event at all.
    const { rerender } = render(<ReviewCard {...REVIEW} tone="emphasized" />);

    const article = screen.getByRole('article', { name: REVIEW.title });
    const letters = screen.getByText(REVIEW.initials);

    rerender(<ReviewCard {...REVIEW} tone="framed" />);

    expect(screen.getByRole('article', { name: REVIEW.title })).toBe(article);
    expect(screen.getByText(REVIEW.initials)).toBe(letters);
    expect(article.querySelector('img')).toBeNull();
  });

  it('dresses each tone in ui/Card’s row and nothing else', () => {
    render(<ReviewCard {...REVIEW} tone="framed" />);

    const tokens = tokensOf(screen.getByRole('article'));
    expect(tokens).toContain(RADIUS);
    for (const token of FRAMED) expect(tokens).toContain(token);
    // The atom's own axis is what the section asks for — never a fifth look
    // spelled here: `bg-page` and the flat `border-line-subtle` belong to
    // tones this component may not wear.
    expect(tokens).not.toContain('bg-page');
    expect(tokens).not.toContain('border-line-subtle');
  });
});

describe('ReviewCard — the card is an <article> named by its own title', () => {
  it('pairs the article with the <h3> through a derived id', () => {
    render(<ReviewCard {...REVIEW} tone="framed" />);

    const article = screen.getByRole('article', { name: REVIEW.title });
    const heading = screen.getByRole('heading', {
      level: 3,
      name: REVIEW.title,
    });

    expect(article.tagName).toBe('ARTICLE');
    expect(heading.tagName).toBe('H3');
    expect(heading).toHaveAttribute('id', 'review-andreea-popescu-title');
    expect(article).toHaveAttribute('aria-labelledby', heading.id);
    expect(article).toContainElement(heading);
    // `id` names a REVIEW here, not an element (it is Omitted from the native
    // attributes): nothing may leak onto the root.
    expect(article).not.toHaveAttribute('id');
  });

  it('dresses the h3 in ui/Heading’s `title` step and opens ONE outline slot', () => {
    render(<ReviewCard {...REVIEW} tone="framed" />);

    const heading = screen.getByRole('heading', { level: 3 });
    expect(tokensOf(heading)).toEqual(TITLE_STEP);
    // One heading per card — the reviewer's name below wears the same look on
    // a <p> (ledger D7), which is the whole reason that decision exists.
    expect(screen.getAllByRole('heading')).toHaveLength(1);
  });

  it('keeps every string intact, Ș ș Ț ț ă â î and all', () => {
    render(
      <ReviewCard
        {...REVIEW}
        tone="framed"
        title={RO_ALL}
        body={RO_ALL}
        name={RO_ALL}
        procedure={RO_ALL}
      />,
    );

    expect(screen.getByRole('article', { name: RO_ALL })).toBeInTheDocument();
    expect(screen.getAllByText(RO_ALL)).toHaveLength(4);
  });
});

describe('ReviewCard — the header row: the disc and the stars', () => {
  it('names the star row with the band’s finished ICU sentence', () => {
    render(<ReviewCard {...REVIEW} tone="framed" />);

    const stars = screen.getByRole('img', { name: REVIEW.ratingLabel });
    expect(stars).toBeInTheDocument();
    // The section never formats a number: the comma in "4,5" arrived with the
    // string (§8.1). Nothing here may print the raw value.
    expect(screen.queryByText('4.5')).toBeNull();
  });

  it('hides the letters face from assistive tech — the caption prints the name', () => {
    render(<ReviewCard {...REVIEW} tone="framed" />);

    const letters = screen.getByText(REVIEW.initials);
    expect(letters).toHaveAttribute('aria-hidden', 'true');
    // …so the name is announced exactly once, by the caption.
    expect(
      screen.getByRole('article', { name: REVIEW.title }).textContent,
    ).toContain(REVIEW.name);
  });

  it('renders the photograph inside the disc when the review carries one', () => {
    // Synchronous, before the runner's 404 swaps the face (see the header).
    render(<ReviewCard {...REVIEW} picture={PICTURE} tone="framed" />);

    const article = screen.getByRole('article');
    const picture = article.querySelector('img');
    expect(picture).not.toBeNull();
    expect(picture?.getAttribute('alt')).toBe('');
    expect(screen.queryByText(REVIEW.initials)).toBeNull();
  });
});

describe('ReviewCard — the quoted body and its credential', () => {
  it('wraps the body in <blockquote> inside the <figure>', () => {
    const { container } = render(<ReviewCard {...REVIEW} tone="framed" />);

    const body = screen.getByText(REVIEW.body);
    expect(body.tagName).toBe('P');
    expect(body.parentElement?.tagName).toBe('BLOCKQUOTE');
    expect(body.closest('figure')).toBe(container.querySelector('figure'));
    // …and the two `flex-1`s that pin the credential to the bottom edge.
    expect(container.querySelector('figure')?.className).toBe(FIGURE);
    expect(body.parentElement?.className).toBe(BLOCKQUOTE);
  });

  it('carries the two quote utilities — and NO quote mark in the string (D6)', () => {
    render(<ReviewCard {...REVIEW} tone="framed" />);

    const body = screen.getByText(REVIEW.body);
    expect(tokensOf(body)).toEqual(BODY_RECIPE);
    // The marks are GENERATED: they come from `quotes: auto` against the
    // document's language, so the rendered text — everything the DOM actually
    // holds — carries none of them, in any of the five languages. A string
    // that brought its own would render inside the generated pair.
    expect(screen.getByRole('article').textContent).not.toMatch(/["'„”“«»]/);
  });

  it('puts the name and the procedure in the <figcaption>, under the thin rule', () => {
    const { container } = render(<ReviewCard {...REVIEW} tone="framed" />);

    const caption = container.querySelector('figcaption') as HTMLElement;
    expect(caption.className).toBe(FIGCAPTION);
    expect(caption).toContainElement(screen.getByText(REVIEW.name));
    expect(caption).toContainElement(screen.getByText(REVIEW.procedure));
  });

  it('renders the name as a <p> wearing the title step — never a heading (D7)', () => {
    render(<ReviewCard {...REVIEW} tone="framed" />);

    const name = screen.getByText(REVIEW.name);
    expect(name.tagName).toBe('P');
    // Heading's title recipe plus the ONE deliberate extra: `hyphens-none` — a proper
    // noun never breaks at a foreign dictionary's syllables (G2 a11y NIT, §15.14's spirit).
    expect(tokensOf(name)).toEqual([...TITLE_STEP, 'hyphens-none']);
    expect(screen.queryByRole('heading', { name: REVIEW.name })).toBeNull();
  });

  it('renders the procedure through ui/Eyebrow — uppercase in CSS, never in the string', () => {
    render(<ReviewCard {...REVIEW} tone="framed" />);

    const procedure = screen.getByText(REVIEW.procedure);
    expect(procedure.tagName).toBe('P');
    expect(procedure.className).toBe(EYEBROW_RECIPE);
    // Sentence case as given: the browser owns Ș/Ț case mapping, which is why
    // no toUpperCase() may ever appear on this path.
    expect(procedure.textContent).toBe(REVIEW.procedure);
  });
});

describe('ReviewCard — §6 fidelity: placement in, no styling out', () => {
  it('merges the caller className LAST, onto the article itself', () => {
    // `h-full` is the real thing the deck passes: every card in a row equals
    // the tallest, which is placement (§6.8), not the card's own geometry.
    render(<ReviewCard {...REVIEW} tone="framed" className="h-full" />);

    const tokens = tokensOf(screen.getByRole('article'));
    expect(tokens.at(-1)).toBe('h-full');
    expect(tokens).toContain(RADIUS);
  });

  it('spreads remaining native props onto the article, not onto the atoms', () => {
    // `lang` is the shape the German story uses: CSS `hyphens: auto` picks its
    // dictionary from the element's declared language and inherits down, and
    // `quotes: auto` picks the quote marks from the same attribute (D6).
    render(
      <ReviewCard
        {...REVIEW}
        tone="framed"
        lang="de"
        data-slot="review-card"
      />,
    );

    const article = screen.getByRole('article');
    expect(article).toHaveAttribute('lang', 'de');
    expect(article).toHaveAttribute('data-slot', 'review-card');
    expect(screen.getByRole('heading', { level: 3 })).not.toHaveAttribute(
      'lang',
    );
  });

  it('accepts ref as a regular prop (React 19) — it is the <article>', () => {
    const root = createRef<HTMLElement>();
    render(<ReviewCard {...REVIEW} tone="framed" ref={root} />);

    expect(root.current?.tagName).toBe('ARTICLE');
    expect(root.current).toContainElement(
      screen.getByRole('heading', { level: 3 }),
    );
  });

  it('owns no outer margin anywhere — the deck’s track owns spacing (§6.4)', () => {
    const { container } = render(<ReviewCard {...REVIEW} tone="framed" />);

    for (const element of container.querySelectorAll('*')) {
      for (const token of tokensOf(element)) {
        expect(token).not.toMatch(/^-?m[trblxyse]?-/);
      }
    }
  });

  it('carries no responsive self-scaling — media queries are the page’s (§6.5)', () => {
    // The old card scaled its own padding (`p-5 sm:p-7`); ui/Card's single
    // inset replaced it, and this is the guard that keeps the axis closed.
    const { container } = render(
      <ReviewCard {...REVIEW} picture={PICTURE} tone="emphasized" />,
    );

    for (const element of container.querySelectorAll('*')) {
      for (const token of tokensOf(element)) {
        expect(token).not.toMatch(/(^|:)(max-)?(sm|md|lg|xl|2xl):/);
      }
    }
  });
});

describe('ReviewCard — zero islands of its own, zero message keys', () => {
  it('ships NO client directive — the deck is the island, not the card (§16)', () => {
    // The source guard, read through Vite's ?raw (typed by the repo's own
    // src/types/raw-import.d.ts) so it runs in the same browser project as the
    // rest of the suite. Anchored to a line of its OWN, because that is what a
    // directive is, and tolerant of a trailing comment.
    expect(CODE).not.toMatch(
      /^\s*['"]use client['"]\s*;?\s*(\/\/.*|\/\*.*)?$/m,
    );
    // …and the reasons it can stay that way: no hook, no handler, no t().
    expect(CODE).not.toMatch(/\buse[A-Z]\w*\(/);
    expect(CODE).not.toMatch(/\bon[A-Z]\w*=/);
    expect(CODE).not.toMatch(/\buseTranslations\b/);
    expect(CODE).not.toMatch(/\bt\(/);
  });

  it('imports EXACTLY the six atoms it composes plus the two value types', () => {
    // The import surface is the guard that sees what a regex cannot. One of
    // these SIX carries a client directive of its own — ui/Avatar, for its
    // picture→letters fallback — so the card costs the page that atom's island
    // and nothing else; adding an import here has to be a deliberate edit to
    // this test, with that question asked out loud. lib/initials and lib/rating
    // arrive as TYPES only, which is also why no lib DATA (lib/reviews) is
    // reachable from this tier: the band binds the list, the card takes props.
    const specifiers = [
      ...CODE.matchAll(/^import\s[^'"]*from\s*['"]([^'"]+)['"]/gm),
    ]
      .map((match) => match[1])
      .toSorted();

    expect(specifiers).toEqual([
      '@/components/ui/Avatar/Avatar',
      '@/components/ui/Card/Card',
      '@/components/ui/Eyebrow/Eyebrow',
      '@/components/ui/Heading/Heading',
      '@/components/ui/StarRating/StarRating',
      '@/components/ui/Text/Text',
      '@/lib/initials/initials',
      '@/lib/rating/rating',
      'react',
    ]);
    // Side-effect (`import './x'`) and re-export (`export … from './x'`) forms
    // add a dependency the matcher above would not see.
    expect(CODE).not.toMatch(/^import\s*['"]/m);
    expect(CODE).not.toMatch(/^export\s[^=]*\sfrom\s/m);
  });

  it('renders nothing interactive: a card is read, never pressed', () => {
    render(<ReviewCard {...REVIEW} picture={PICTURE} tone="framed" />);

    expect(screen.queryAllByRole('button')).toHaveLength(0);
    expect(screen.queryAllByRole('link')).toHaveLength(0);
  });

  it('never renders a message key path — every string is a prop (§8.1)', () => {
    // next-intl prints the dotted key on a miss; there is no t() here at all,
    // and this is the assertion that keeps it that way.
    const { container } = render(<ReviewCard {...REVIEW} tone="framed" />);

    expect(container.textContent).toBe(
      `${REVIEW.initials}${REVIEW.title}${REVIEW.body}${REVIEW.name}${REVIEW.procedure}`,
    );
    expect(container.textContent).not.toMatch(/\b[a-z]+\.[a-zA-Z]+\.[a-zA-Z]+/);
  });
});

describe('ReviewCard — type-level pins', () => {
  it('pins the deliberate type decisions so a refactor cannot quietly widen them', () => {
    // Erased to no-ops at runtime; they fail at `tsc --noEmit` time, naming
    // the property.
    // `tone` is REQUIRED and is drawn from ui/Card's axis through a
    // `satisfies`-checked tuple — NOT an `Extract`, which would filter a
    // renamed row silently: renaming a row in the atom must break this file,
    // and a deck that forgets the prop must not compile into a wrong slide.
    expectTypeOf<ReviewTone>().toEqualTypeOf<'framed' | 'emphasized'>();
    // The article is named by its own <h3>: a caller can neither rename it
    // nor tooltip it (PersonnelCard D4 applied; G3 typescript L2/N4).
    expectTypeOf<ReviewCardProps>().not.toHaveProperty('aria-labelledby');
    expectTypeOf<ReviewCardProps>().not.toHaveProperty('aria-label');
    expectTypeOf<ReviewCardProps['title']>().toEqualTypeOf<string>();
    expectTypeOf<ReviewCardProps>()
      .toHaveProperty('tone')
      .toEqualTypeOf<ReviewTone>();
    expectTypeOf<ReviewCardProps>()
      .toHaveProperty('rating')
      .toEqualTypeOf<Rating>();
    // `children` is Omitted: content arrives as named props, and without the
    // Omit a caller could nest something, type-check, and watch it vanish
    // (JSX children always beat spread ones — the SectionHeading precedent).
    expectTypeOf<ReviewCardProps>().not.toHaveProperty('children');
  });
});
