import type { ComponentPropsWithRef, ReactElement } from 'react';
import { Avatar } from '@/components/ui/Avatar/Avatar';
import { Card, type CardTone } from '@/components/ui/Card/Card';
import { Eyebrow } from '@/components/ui/Eyebrow/Eyebrow';
import { Heading } from '@/components/ui/Heading/Heading';
import { StarRating } from '@/components/ui/StarRating/StarRating';
import { Text } from '@/components/ui/Text/Text';
import type { Initials } from '@/lib/initials/initials';
import type { Rating } from '@/lib/rating/rating';

// sections/ReviewCard — ONE review as a card: the reviewer's disc and their
// stars on one row, the review's own title, the quoted body, a thin rule, and
// underneath it the patient's name over the procedure they came for. Built to
// the owner-approved N2 composition contract (master board fb-432…448,
// dossier .claude/section-runs/2026-09-10_17-01_reviews-carousel/sections/
// ReviewCard.md, approved 2026-09-10) out of the old site's
// composite/review-card, whose brief was one sentence: "follow the exact
// pattern the old card looks like, aspect wise".
//
// ── TIER: THE SHARED-COMPOSITION SUB-KIND (§4), the Wordmark/SectionHeading
// row. It composes atoms, binds no site data, and calls NO t() — every string
// arrives FINISHED from the band that owns the message keys (§8.1), the
// rating's sentence included (`ratingLabel`, "4,5 din 5 stele", already
// through ICU and already carrying the comma its locale uses). One consumer
// today, sections/ReviewsCarousel; reuse never promotes a composite to `ui/`
// (§4's corrected promotion rule), so a second consumer would only schedule it
// earlier, never move it.
//
// ── THE MORPH IS THE WHOLE POINT (ledger D1a, the owner's pitfall). The deck
// marks its current slide by handing this card a different `tone` — `framed`
// when idle, `emphasized` when selected — and NOTHING ELSE about the card may
// change: same DOM node, same photograph, same words, same box. Two decisions
// carry that:
//   · `tone` is a REQUIRED prop with no default. The deck decides which look
//     each card wears; a default here would let a caller forget, and a
//     forgotten slide is a wrong slide rather than a missing one.
//   · both values come from ONE ui/Card axis, so the swap is a class change on
//     an element React keeps. The atom's sum rule (border width + padding =
//     25px on every row) is what makes it cost zero pixels: `framed` spends
//     3 + 22 where `emphasized` spends 1 + 24, so the content box never moves
//     and a framed card in a row still lines its text edges up with its
//     neighbours'. ReviewCard.test.tsx pins the node identity across the flip
//     in BOTH directions; ui/Card's own suite pins the 25px.
// `ReviewTone` is derived from a tuple that `satisfies readonly CardTone[]`
// rather than from a fresh union or an `Extract`: an `Extract` filters
// SILENTLY (rename `framed` in the atom and `Extract<CardTone, 'framed' |
// 'emphasized'>` quietly becomes `'emphasized'`), whereas the tuple makes THIS
// file the one that stops compiling the day the atom renames a row (G2 ts
// L3, 2026-09-10).
//
// ── THE QUOTE MARKS ARE CSS, NOT STRING (ledger D6). The body arrives BARE —
// no „", no “”, no «» — and the marks are generated by
// `before:content-[open-quote]` / `after:content-[close-quote]` on the body
// element, which the engine resolves through the `quotes: auto` default
// against the element's declared language. Measured in this repo's own
// Chromium (2026-09-10, via the CDP accessibility tree, which is where
// generated content becomes readable): ro → „…” · de → „…“ · fr → «…» · en →
// “…”. The old card hardcoded `&ldquo;…&rdquo;` — English marks on a Romanian
// site, in five locales at once. Consequence for every consumer, stated here
// because it is invisible at the call site: a `body` string that carries its
// own quote marks renders them INSIDE the generated pair. The message files
// hold the sentence, the stylesheet holds the punctuation.
//
// ── THE CREDENTIAL BLOCK. `<figure>` + `<blockquote>` + `<figcaption>` is
// HTML's own testimonial shape — the quoted voice and the attribution of that
// voice, related by the element rather than by proximity. Two riders:
//   · `flex-1` TWICE, and both are load-bearing (owner 2026-09-12, pack round
//     2: "the name of the patient and the operation sticky to the bottom of
//     the card, and the compensation space to come from the text of the
//     review"). The FIGURE's `flex-1` takes the card's slack — the card is a
//     flex column and the figure is the child that grows; the BLOCKQUOTE's
//     `flex-1` takes the figure's slack, so the room opens up BELOW the
//     quoted text and the caption is pushed to the figure's end. The first
//     spelling had only the first: the caption sat right under the quote and
//     the slack collected under the caption, so the rule, the name and the
//     procedure landed at a different height on every card. With both, every
//     card of a deck whose cards share one height (the deck's stage — the
//     tallest card sets it) puts the thin rule, the name and the procedure at
//     the SAME distance from its bottom edge. ReviewCard.test.tsx pins both
//     utilities. The card's HEIGHT stays the deck's business (`h-full`
//     through className, §6.8) — ui/Card refuses a height prop for the same
//     reason (its D4), and a German review is 30–35% longer than an English
//     one.
//   · the "thin horizontal line" of the old card is the caption's own
//     `border-t`, not a separator element: it belongs to the credential, so it
//     travels with it and no <hr> has to be kept in position.
//
// ── THE NAME IS NOT A HEADING (ledger D7, owner). It WEARS ui/Heading's
// `title` step — 20px display type, the same treatment the review's own title
// wears — on that atom's default `<p>` host, so the document outline gains
// exactly one entry per card: the `<h3>`. A dozen reviewer names in the
// outline would bury the band's own `<h2>` under a list of patients, and the
// name is already announced as part of the figure it captions. This is the
// Footer's column-title precedent (a `<p>` wearing the title look), one tier
// up; §9's "logical heading order" is about the outline, never about size.
//
// ── THE `<h3>` AND THE ARTICLE'S NAME. `aria-labelledby` points at the
// review's own title, so the card announces itself as "Au văzut imaginea de
// ansamblu, article" instead of as a nameless box in a list of nameless
// boxes. The id is derived, never passed: `review-${id}-title` — unique
// because review ids are unique (lib/reviews' `id` field, the deck's React key
// as well), which is also why the native `id` attribute is Omitted from the
// props below. h3 because the band opens with the h2 (§9).
//
// ── WHAT THIS SECTION DOES NOT OWN. No outer margin and no width (§6.4/§6.8 —
// the deck's slide track measures the card); no `sm:`/`lg:` self-scaling (the
// old card's `p-5 sm:p-7` became ui/Card's single inset); no text alignment of
// its own — the body is start-aligned by the globals' prose fence (§15.1; the
// old `text-justify` is deliberately NOT ported), and `hyphens: auto` is
// inherited from the body tier (§15.14), which is what lets a German compound
// break inside the card instead of pushing its border.
//
// ── ZERO ISLANDS OF ITS OWN (§16): no 'use client', no hook, no handler, no
// state — ReviewCard.test.tsx's ?raw guard pins the directive's absence
// mechanically, because no runtime assertion can see it. The card is inert
// HTML that the deck (the island) re-renders; ui/Avatar carries its own
// directive for its picture→letters fallback, which is that atom's decision
// and is written out in its header.

/**
 * The two looks a review can wear, idle and selected — each one a real Card
 * row, checked here. Exported for the stories' tone control, so the panel
 * offers exactly this pair and nothing the deck never asks for.
 */
export const REVIEW_TONES = [
  'framed',
  'emphasized',
] as const satisfies readonly CardTone[];
export type ReviewTone = (typeof REVIEW_TONES)[number];

export type ReviewCardProps = {
  /**
   * The stable review id — the deck's React key AND the seed of the
   * `aria-labelledby` pair. The native `id` attribute is Omitted below so the
   * two can never be confused: this one names a review, not an element.
   */
  id: string;
  /** Which look the deck asks for. REQUIRED — the deck decides, per slide. */
  tone: ReviewTone;
  /** Exactly two capitals, the reviewer's own — never derived from the name. */
  initials: Initials;
  /**
   * Optional portrait, path under `public/images/` (§11). Decorative in the
   * deck, which passes `alt=""`: the name is printed two lines below.
   */
  picture?: { src: `/images/${string}`; alt: string };
  /** Whole or half stars, 0 to 5. */
  rating: Rating;
  /** Finished ICU output, e.g. "4,5 din 5 stele" (§8.1) — never a number. */
  ratingLabel: string;
  /** The review's own title. Finished, already-translated text (§8.1). */
  title: string;
  /** The quoted body, WITHOUT quote marks — the stylesheet adds them (D6). */
  body: string;
  /** The patient's name, as they consented to have it shown. */
  name: string;
  /** The procedure label, sentence case — ui/Eyebrow uppercases in CSS. */
  procedure: string;
  // `title` is the ONE own name that also exists natively (HTMLAttributes'
  // tooltip string — `name` is not on this element's attributes at all,
  // checked); it is Omitted from the native half so the shadowing is SPELLED
  // rather than left to intersection arithmetic, and `rest` carries only
  // what HTML meant. `aria-label` / `aria-labelledby` are Omitted too: the
  // article is NAMED BY ITS OWN <h3> (below), and a caller's value would land
  // after it in the spread — the sibling section's precedent
  // (sections/PersonnelCard, its D4: "the article's name is the heading's
  // alone"), applied so the two cards named by their heading say one thing
  // (G3 typescript L2). ReviewCard.test.tsx pins all three.
} & Omit<
  ComponentPropsWithRef<'article'>,
  'id' | 'children' | 'title' | 'aria-label' | 'aria-labelledby'
>;

export function ReviewCard({
  id,
  tone,
  initials,
  picture,
  rating,
  ratingLabel,
  title,
  body,
  name,
  procedure,
  className,
  ...rest
}: ReviewCardProps): ReactElement {
  const titleId = `review-${id}-title`;

  // THE DISC'S PROPS, ASSEMBLED AS A VALUE rather than spread in the JSX, and
  // the reason is a real TypeScript limit rather than taste: ui/Avatar models
  // the picture and its alt as a DISCRIMINATED PAIR ({src, alt} | {src?:
  // never, alt?: never}), so a picture without its alt is unspellable. A JSX
  // spread of `picture ?? {}` collapses that pair into two INDEPENDENTLY
  // optional members — `src?: string | undefined` — which is exactly the shape
  // the union refuses, and the call site fails to compile even though it is
  // correct (measured, this lane: TS2322 against the no-picture constituent).
  // Assembled here the union survives the ternary, both constituents check,
  // and the guarantee stays the atom's instead of being re-derived here.
  const face = picture ? { initials, ...picture } : { initials };

  return (
    // asChild: the card IS the <article> (ui/Card D2, through ui/slot.ts), so
    // no wrapper div sits between the deck's slide and the card's semantics.
    // className is the DECK's placement (`h-full`) and rides through the atom,
    // which merges it LAST — §6.8's convention, pinned by the tests.
    // `aura={false}` is spelled rather than left to the default (ledger D13):
    // the glow is chosen per card KIND in the section that composes it (owner
    // fb-378/381), and this kind's answer is no — a lavender halo behind a
    // 3px lavender frame would smear the frame the owner asked to keep.
    <Card asChild tone={tone} aura={false} className={className}>
      <article
        // Before the spread, like ui/Avatar's aria-hidden: the pairing is this
        // component's contract, and a caller with a stranger case may still
        // say otherwise (§6.8 native-element fidelity). `rest` lands HERE —
        // the article is the root — never on the atoms inside.
        aria-labelledby={titleId}
        {...rest}
      >
        {/* The old card's header row: the disc on the reading edge, the stars
            pushed to the other one. `items-center` is what keeps a 3rem disc
            and a 1rem star row optically on one line. */}
        <div className="flex items-center justify-between gap-3">
          {/* One element for both faces (see `face` above): with a picture the
              disc shows the photograph, without one the two capitals — same
              3rem circle either way, aria-hidden on the letters because the
              name is printed in the caption below (ui/Avatar's D-A1). */}
          <Avatar {...face} />
          <StarRating value={rating} aria-label={ratingLabel} />
        </div>
        <Heading asChild size="title">
          <h3 id={titleId}>{title}</h3>
        </Heading>
        <figure className="flex flex-1 flex-col gap-3">
          {/* `flex-1`: the quote is where the card's compensation space goes
              (the CREDENTIAL BLOCK rider in the header) — the caption below
              it therefore sits at the bottom of every card in a deck. */}
          <blockquote className="flex-1">
            {/* The two utilities are the section's own PUNCTUATION, not a
                restyling of ui/Text's internals (§6.8): they add generated
                content around the atom's host element and touch none of its
                ink, size or leading. */}
            <Text
              tone="muted"
              className="before:content-[open-quote] after:content-[close-quote]"
            >
              {body}
            </Text>
          </blockquote>
          {/* THE THIN RULE — the old card's separator, owned by the credential
              it separates. `gap-0.5` is the tight name/procedure pair, tighter
              than the card's own rhythm on purpose: those two lines are one
              block of information. */}
          <figcaption className="flex flex-col gap-0.5 border-t border-line-subtle pt-3">
            {/* `hyphens-none` (G2 a11y NIT): a Romanian surname under a German page would
                otherwise break at a foreign dictionary's syllables — the §15.14 rider's spirit,
                per-element (§15.15 b). */}
            <Heading size="title" className="hyphens-none">
              {name}
            </Heading>
            <Eyebrow>{procedure}</Eyebrow>
          </figcaption>
        </figure>
      </article>
    </Card>
  );
}
