import { createRef } from 'react';
import { fireEvent, render, screen, within } from '@testing-library/react';
import { describe, expect, expectTypeOf, it, vi } from 'vitest';
// The REAL stylesheet, compiled by the same Tailwind pipeline the site uses.
// The "one shape, two faces" pin below is meaningless without it: 3rem is a
// COMPUTED length, and the whole promise of this atom is that the letters
// face and the picture face resolve to the same box — never a class name.
// tests/setup/components.ts loads no CSS globally; the per-file import is the
// house pattern (Card, Modal, SpeedDial, LanguageSwitcher, the shell).
import '@/styles/globals.css';
import type { Initials } from '@/lib/initials/initials';
import { Avatar, type AvatarProps } from './Avatar';
import source from './Avatar.tsx?raw';

// ── HARNESS NOTE — the `process` shim, inherited from Image.test.tsx (read its
// full argument there; this file is the second consumer of the same fact). The
// `components` vitest project is bare Vite in a real chromium: no Next plugin,
// so nothing defines `process`, and next/image reads
// process.env.__NEXT_IMAGE_OPTS at MODULE scope. Avatar composes ui/Image, so
// importing THIS component drags that read in and the file dies before a
// single test runs without the shim. vi.hoisted is the sanctioned pre-import
// seam. Deliberately EMPTY env: with __NEXT_IMAGE_OPTS undefined, next/image
// falls back to its own defaults instead of this file pretending to be a
// second source of truth for the build config.
vi.hoisted(() => {
  if (!('process' in globalThis)) {
    Object.defineProperty(globalThis, 'process', {
      value: { env: {} },
      configurable: true,
      writable: true,
    });
  }
});

// ── WHAT THE PICTURE FACE ACTUALLY DOES IN THIS RUNNER, and why every picture
// assertion is SYNCHRONOUS. The optimized URLs the loader emits
// (/images/…/nextImageExportOptimizer/…-opt-<w>.WEBP) do not exist here — that
// folder is generated by `npm run build` and gitignored — so every <img> 404s
// and a REAL error event is delivered at a macrotask boundary, which then
// trips this atom's own fallback. Read the DOM right after render and no
// `await` between the two, exactly as Image.test.tsx records for its
// placeholder pins. The deliberate error below is fired by hand instead of
// waited for, so the swap is tested as a mechanism rather than as a race.

// Fixtures are Romanian WITH diacritics (§15.7): Andreea Popescu and Ștefan
// Toma are the dossier's two reviewer fixtures, and Ș/Ț are exactly the marks
// that only exist in their comma-below form (U+0218/U+021A) — a broken
// encoding path (font subsetting, JSX escaping, the message pipeline) fails
// here rather than in front of a patient. ÄÖ is the accented stress pair (DE's
// contribution: two letters cannot be "longest", but they can be non-ASCII).
const RO_INITIALS = 'AP';
const RO_DIACRITICS = 'ȘT';
const ACCENTED = 'ÄÖ';

// The committed demo photograph, reused rather than a reviewer's face: real
// reviewer pictures are the owner's to supply (§11 photographs gate).
const PHOTO = '/images/demo/hero-calm.jpg' as const;
const PHOTO_ALT = 'Portret pacient, fotografie de profil';

// THE recipes, in canonical order and written out rather than imported — the
// Eyebrow RECIPE convention: this file must fail on a silent edit to the
// component's constants, which an import would happily follow.
const DISC =
  'inline-flex size-12 shrink-0 items-center justify-center overflow-hidden rounded-full';
const LETTERS =
  'bg-cta text-base font-semibold text-ink-inverse uppercase select-none';
const PICTURE = 'size-full rounded-full border border-line-subtle object-cover';

const tokensOf = (element: Element) =>
  element.className.split(/\s+/).filter(Boolean);

/** The host, reached through the render container: a <span> has no role, and
 *  that is the contract — the disc adds no semantics of its own. The instanceof
 *  check is the tag assertion, done once here instead of in every case. */
const discOf = (container: HTMLElement): HTMLSpanElement => {
  const disc = container.firstElementChild;
  if (!(disc instanceof HTMLSpanElement)) {
    throw new Error(
      `Avatar test: expected a <span> host, got ${disc?.tagName}`,
    );
  }
  return disc;
};

const pictureIn = (container: HTMLElement) => container.querySelector('img');

/** The cast a data seam performs: initials that arrive from outside
 *  TypeScript's reach (a JSON list, a future lib/reviews module) are plain
 *  strings. Every runtime-belt case below goes through this door on purpose —
 *  the compile-time half is pinned separately, in the type probes. */
const fromDataSeam = (value: string) => value as Initials;

const boxOf = (element: Element) => {
  const { width, height } = getComputedStyle(element);
  return `${width} × ${height}`;
};

describe('Avatar — one shape, two faces', () => {
  it('renders the letters as given inside a <span>, diacritics intact (Ș Ț)', () => {
    const { container } = render(<Avatar initials={RO_DIACRITICS} />);
    const disc = discOf(container);
    // Query the diacritics themselves: a normalising or mangling layer would
    // lose the node here rather than in front of a patient.
    expect(screen.getByText(RO_DIACRITICS)).toBe(disc);
    expect(disc).toHaveTextContent(RO_DIACRITICS);
    expect(pictureIn(container)).toBeNull();
  });

  it('renders a picture when one is given, named by its alt', () => {
    const { container } = render(
      <Avatar initials={RO_INITIALS} src={PHOTO} alt={PHOTO_ALT} />,
    );
    // Name-scoped role query: this is what a screen reader announces.
    const picture = within(container).getByRole('img', { name: PHOTO_ALT });
    expect(picture.tagName).toBe('IMG');
    expect(picture.parentElement).toBe(discOf(container));
    // The letters are NOT also in the DOM: one face at a time, so a
    // half-loaded photo can never show two letters through it.
    expect(discOf(container)).not.toHaveTextContent(RO_INITIALS);
  });

  it('takes alt="" — a decorative picture, the deck default (D-A1)', () => {
    // The a11y-correct marking for a picture whose information the card
    // already prints: assistive tech skips it entirely (implicit role
    // `presentation`). An empty alt is a decision, not a missing string.
    const { container } = render(
      <Avatar initials={RO_INITIALS} src={PHOTO} alt="" />,
    );
    expect(within(container).queryByRole('img')).not.toBeInTheDocument();
    const decorative = within(container).getByRole('presentation');
    expect(decorative.tagName).toBe('IMG');
    expect(decorative).toHaveAttribute('alt', '');
  });

  it('measures the SAME 3rem circle in both faces (the atom’s whole promise)', () => {
    // Real CSS, computed: a card whose reviewer has no photograph must line up
    // with the one beside it, and the header row must not move when a picture
    // 404s mid-list. Class names cannot prove that; lengths can.
    const { container: lettersBox } = render(<Avatar initials={RO_INITIALS} />);
    const { container: pictureBox } = render(
      <Avatar initials={RO_INITIALS} src={PHOTO} alt="" />,
    );
    expect(boxOf(discOf(lettersBox))).toBe('48px × 48px');
    expect(boxOf(discOf(pictureBox))).toBe(boxOf(discOf(lettersBox)));
  });

  it('emits exactly the disc + letters recipe on the letters face', () => {
    render(<Avatar initials={RO_INITIALS} />);
    expect(screen.getByText(RO_INITIALS).className).toBe(`${DISC} ${LETTERS}`);
  });

  it('emits the disc recipe ALONE on the picture face — no ground, no ink', () => {
    // The green face is the fallback's face. Painting it behind a photograph
    // would show as a coloured rim wherever `object-cover` leaves a hairline.
    const { container } = render(
      <Avatar initials={RO_INITIALS} src={PHOTO} alt="" />,
    );
    expect(discOf(container).className).toBe(DISC);
  });

  it('dresses the photograph itself: fills, crops, rounds, 1px ring (D-A4)', () => {
    const { container } = render(
      <Avatar initials={RO_INITIALS} src={PHOTO} alt={PHOTO_ALT} />,
    );
    const picture = within(container).getByRole('img', { name: PHOTO_ALT });
    // The ring is on the PICTURE only — it separates a light photo edge from a
    // light card, which a solid green disc does not need.
    expect(picture.className).toBe(PICTURE);
    expect(picture).toHaveAttribute('width', '48');
    expect(picture).toHaveAttribute('height', '48');
    // `sizes` is load-bearing, not decoration: without it the browser assumes
    // 100vw and over-downloads a 3rem box (§10.6).
    expect(picture).toHaveAttribute('sizes', '3rem');
  });

  it('owns no outer margin (§6.4 — the card’s row owns the gap)', () => {
    render(<Avatar initials={RO_INITIALS} />);
    const tokens = tokensOf(screen.getByText(RO_INITIALS));
    expect(tokens.filter((t) => /^-?m[trblxyse]?-/.test(t))).toEqual([]);
  });

  it('carries no responsive or container self-scaling (§6.5)', () => {
    // An atom cannot see its container: a second size joins as an additive
    // prop with 3rem pinned as the default, never as a breakpoint inside.
    render(<Avatar initials={RO_INITIALS} />);
    const tokens = tokensOf(screen.getByText(RO_INITIALS));
    expect(
      tokens.filter((t) => /^(sm|md|lg|xl|2xl|@[a-z0-9]+):/.test(t)),
    ).toEqual([]);
  });
});

describe('Avatar — the letters are decoration (D-A1, §9)', () => {
  it('hides the letters face from assistive tech', () => {
    // The card prints the reviewer's name two lines below; a disc that
    // announced it again would make every testimonial read its author twice.
    render(<Avatar initials={RO_DIACRITICS} />);
    expect(screen.getByText(RO_DIACRITICS)).toHaveAttribute(
      'aria-hidden',
      'true',
    );
  });

  it('leaves the picture face VISIBLE to assistive tech', () => {
    // Otherwise a consumer who passes a real alt would never be heard. A
    // decorative picture removes itself through alt="" instead, one layer
    // down where the a11y contract for images lives.
    const { container } = render(
      <Avatar initials={RO_INITIALS} src={PHOTO} alt={PHOTO_ALT} />,
    );
    expect(discOf(container)).not.toHaveAttribute('aria-hidden');
    expect(
      within(container).getByRole('img', { name: PHOTO_ALT }),
    ).toBeInTheDocument();
  });

  it('lets a consumer override aria-hidden through the native spread (§6.8)', () => {
    render(<Avatar initials={RO_INITIALS} aria-hidden={false} />);
    expect(screen.getByText(RO_INITIALS)).toHaveAttribute(
      'aria-hidden',
      'false',
    );
  });
});

describe('Avatar — uppercase is CSS, never the string', () => {
  it.each([RO_INITIALS, RO_DIACRITICS, ACCENTED])(
    'leaves %s in the DOM exactly as authored',
    (initials) => {
      render(<Avatar initials={initials as Initials} />);
      const disc = screen.getByText(initials);
      expect(disc.textContent).toBe(initials);
      expect(tokensOf(disc)).toContain('uppercase');
    },
  );

  it('never calls toUpperCase() — a lowercase pair stays lowercase in the DOM', () => {
    // The type asks for capitals; CSS does the shouting. Case mapping is the
    // browser's job, which matters for a Romanian site whose Ș/Ț have their
    // own comma-below capitals (the Turkish dotted-i is the classic burn).
    // A JS .toUpperCase() in the component would make this query fail.
    render(<Avatar initials={fromDataSeam('ap')} />);
    expect(screen.getByText('ap').textContent).toBe('ap');
  });
});

describe('Avatar — belt one: the type (D2)', () => {
  it('accepts a two-capital pair from every locale in the union', () => {
    expectTypeOf<'AP'>().toExtend<Initials>();
    expectTypeOf<'ȘT'>().toExtend<Initials>();
    expectTypeOf<'ÄÖ'>().toExtend<Initials>();
    expectTypeOf<'ÉÇ'>().toExtend<Initials>();
    expectTypeOf<'ÌÙ'>().toExtend<Initials>();
  });

  it('refuses three letters — the owner’s red squiggle before anything runs', () => {
    // Element CREATION only: JSX does not call the component, so the runtime
    // belt below never fires here and this probe stays purely about types.
    const tooMany = (
      // @ts-expect-error — 'AND' is three letters, not an Initials pair
      <Avatar initials="AND" />
    );
    expect(tooMany).toBeTruthy();
  });

  it('refuses a digit and refuses lowercase', () => {
    const digit = (
      // @ts-expect-error — '1' is not a Cap
      <Avatar initials="A1" />
    );
    const lower = (
      // @ts-expect-error — the type asks for capitals (honest data)
      <Avatar initials="ap" />
    );
    expect(digit).toBeTruthy();
    expect(lower).toBeTruthy();
  });

  it('refuses a picture without its alt (§11, unspellable rather than reviewable)', () => {
    const orphan = (
      // @ts-expect-error — src and alt travel together or not at all
      <Avatar initials="AP" src={PHOTO} />
    );
    expect(orphan).toBeTruthy();
  });

  it('takes no children slot and no aria-label prop', () => {
    // Surgical twins of the @ts-expect-error lines above, which are
    // line-scoped and would swallow ANY error on their expression (G2 LOW,
    // 2026-09-01). These stop compiling the moment the property appears, and
    // name it in the tsc output. Erased to a no-op at runtime.
    // The disc's content IS its two faces; and §6.3's typed-required
    // aria-label binds to INTERACTIVE components — this one never is.
    expectTypeOf<AvatarProps>().not.toHaveProperty('children');
    expectTypeOf<AvatarProps>().toHaveProperty('initials');
    expectTypeOf<AvatarProps>().toHaveProperty('src');
    expectTypeOf<AvatarProps>().toHaveProperty('alt');
    expectTypeOf<AvatarProps>().toHaveProperty('className');
  });
});

describe('Avatar — belt two: the runtime guard (D-A2)', () => {
  it.each(['ABC', 'A', 'A1', ''])(
    'throws a RangeError for %o arriving from a data seam',
    (initials) => {
      // The createClock precedent (lib/clock/clock.ts): bad input dies loudly
      // at the call site instead of rendering a three-letter disc that
      // silently overflows its circle.
      expect(() =>
        render(<Avatar initials={fromDataSeam(initials)} />),
      ).toThrow(RangeError);
    },
  );

  it('names the atom, the rule and the offending value in the message', () => {
    expect(() => render(<Avatar initials={fromDataSeam('AND')} />)).toThrow(
      /^Avatar: initials must be exactly two letters; received "AND"\./,
    );
  });

  it('counts LETTERS, not ASCII: Ș Ä and a lowercase pair all pass', () => {
    // `\p{L}` is any Unicode letter in any script and any case — the guard is
    // about COUNT. Asking for capitals is the type's job, and a locale the
    // union has not met yet must not crash the site.
    expect(() =>
      render(<Avatar initials={fromDataSeam('ȘT')} />),
    ).not.toThrow();
    expect(() =>
      render(<Avatar initials={fromDataSeam('ör')} />),
    ).not.toThrow();
  });
});

describe('Avatar — the picture→letters fallback (D-A3)', () => {
  it('swaps to the letters when the photograph fails to load', () => {
    const { container } = render(
      <Avatar initials={RO_INITIALS} src={PHOTO} alt="" />,
    );
    const picture = pictureIn(container);
    expect(picture).not.toBeNull();

    fireEvent.error(picture as HTMLImageElement);

    // The hole where a face was is now two letters, in the same circle.
    expect(pictureIn(container)).toBeNull();
    expect(discOf(container)).toHaveTextContent(RO_INITIALS);
    expect(boxOf(discOf(container))).toBe('48px × 48px');
  });

  it('the swapped-in face is the full letters face, decoration included', () => {
    // Not a bare string in a naked circle: the fallback must be indis-
    // tinguishable from an avatar that never had a picture at all.
    const { container } = render(
      <Avatar initials={RO_DIACRITICS} src={PHOTO} alt={PHOTO_ALT} />,
    );
    fireEvent.error(pictureIn(container) as HTMLImageElement);
    const disc = discOf(container);
    expect(disc.className).toBe(`${DISC} ${LETTERS}`);
    expect(disc).toHaveAttribute('aria-hidden', 'true');
  });

  it('remembers WHICH src failed, so the next reviewer still gets a photo', () => {
    // The deck rotates reviewers through one mounted Avatar. A boolean
    // "failed" flag would keep every later reviewer on their letters because
    // one earlier photograph was missing — the bug this state shape prevents.
    const { container, rerender } = render(
      <Avatar initials={RO_INITIALS} src={PHOTO} alt="" />,
    );
    fireEvent.error(pictureIn(container) as HTMLImageElement);
    expect(pictureIn(container)).toBeNull();

    rerender(
      <Avatar
        initials={RO_DIACRITICS}
        src="/images/demo/transparent-artwork-cat.png"
        alt=""
      />,
    );
    expect(pictureIn(container)).not.toBeNull();
  });

  it('reads a photograph that died BEFORE the handler existed from the element itself (G3 react L1)', () => {
    // React attaches `error` listeners at hydration and never replays one
    // that fired while the script was still downloading; the ref belt reads
    // `complete` + `naturalWidth` at commit instead. Simulated on the
    // prototype, restored in `finally` so no other test inherits a dead image.
    const complete = Object.getOwnPropertyDescriptor(
      HTMLImageElement.prototype,
      'complete',
    ) as PropertyDescriptor;
    const naturalWidth = Object.getOwnPropertyDescriptor(
      HTMLImageElement.prototype,
      'naturalWidth',
    ) as PropertyDescriptor;
    Object.defineProperty(HTMLImageElement.prototype, 'complete', {
      configurable: true,
      get: () => true,
    });
    Object.defineProperty(HTMLImageElement.prototype, 'naturalWidth', {
      configurable: true,
      get: () => 0,
    });
    try {
      const { container } = render(
        <Avatar initials={RO_INITIALS} src={PHOTO} alt="" />,
      );
      expect(pictureIn(container)).toBeNull();
      expect(discOf(container)).toHaveTextContent(RO_INITIALS);
    } finally {
      Object.defineProperty(HTMLImageElement.prototype, 'complete', complete);
      Object.defineProperty(
        HTMLImageElement.prototype,
        'naturalWidth',
        naturalWidth,
      );
    }
  });

  it("ships the 'use client' directive, on line 1", () => {
    // The exact inverse of Card.test.tsx's absence guard, same mechanics and
    // same reason to exist: a directive is invisible to every runtime
    // assertion in this file, because the components runner has no server
    // tier to leave. Here the directive is LOAD-BEARING — useState above a
    // server boundary is a build error, and the fallback is the reason this
    // atom costs the visitor JavaScript at all (§16). Two assertions: the
    // prologue shape (tolerant of a trailing comment, as Card's is), and the
    // POSITION, because a directive that is not the first statement is not a
    // directive at all — bundlers ignore it silently.
    expect(source).toMatch(/^\s*['"]use client['"]\s*;?\s*(\/\/.*|\/\*.*)?$/m);
    expect(source.split('\n')[0]).toBe("'use client';");
  });
});

describe('Avatar — §6.8 native-element fidelity', () => {
  it('merges the caller className LAST on the letters face', () => {
    // Order is the contract, not an accident: a deterministic convention (not
    // a cascade mechanism — attribute order never decides CSS specificity),
    // and the atom's own classes must survive.
    render(<Avatar initials={RO_INITIALS} className="row-start-1" />);
    expect(screen.getByText(RO_INITIALS).className).toBe(
      `${DISC} ${LETTERS} row-start-1`,
    );
  });

  it('merges the caller className LAST on the picture face too', () => {
    const { container } = render(
      <Avatar
        initials={RO_INITIALS}
        src={PHOTO}
        alt=""
        className="row-start-1"
      />,
    );
    expect(discOf(container).className).toBe(`${DISC} row-start-1`);
  });

  it('accepts ref as a regular prop (React 19), reaching the <span>', () => {
    const disc = createRef<HTMLSpanElement>();
    const { container } = render(<Avatar initials={RO_INITIALS} ref={disc} />);
    expect(disc.current).toBeInstanceOf(HTMLSpanElement);
    expect(disc.current).toBe(discOf(container));
  });

  it('spreads remaining native props onto the rendered <span>', () => {
    render(
      <Avatar
        initials={RO_INITIALS}
        id="recenzent-1"
        lang="ro"
        title="Andreea Popescu"
        data-slot="avatar"
      />,
    );
    const disc = screen.getByText(RO_INITIALS);
    expect(disc).toHaveAttribute('id', 'recenzent-1');
    expect(disc).toHaveAttribute('lang', 'ro');
    expect(disc).toHaveAttribute('title', 'Andreea Popescu');
    expect(disc).toHaveAttribute('data-slot', 'avatar');
  });

  it('never leaks its own props onto the DOM element', () => {
    // React 19 forwards unknown props to the DOM verbatim, so an `initials`
    // that slipped through the spread would surface as an attribute right
    // here — and `src`/`alt` would land on a <span>, which is nonsense.
    const { container } = render(
      <Avatar initials={RO_INITIALS} src={PHOTO} alt={PHOTO_ALT} />,
    );
    const disc = discOf(container);
    expect(disc).not.toHaveAttribute('initials');
    expect(disc).not.toHaveAttribute('src');
    expect(disc).not.toHaveAttribute('alt');
  });
});
