import { createRef } from 'react';
import { render, screen, within } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import { Image, type ImageVariant } from './Image';

// The atom's FIRST tests (contract board image-variants-contract-v2 §4,
// owner-approved 2026-08-20). Role-based queries wherever a role exists (§9):
// a passing test doubles as proof of accessible markup — and for images the
// role IS the a11y contract, since `alt=""` deliberately removes it (D7).
//
// No mock of ExportedImage anywhere in this file: the whole point of ui/Image
// is that it is the ONE wrapper around the build-time optimizer (§11), so the
// tests run the real component and assert on what the browser actually gets.
// Consequence to know when reading failures: the optimized URLs the loader
// emits (/images/…/nextImageExportOptimizer/…-opt-<w>.WEBP) do not exist in
// the test runner — the variants folder is generated by `npm run build` and
// gitignored — so every <img> here 404s and ExportedImage's client fallback
// swaps the original file in. That is ASYNC (a network error event), which is
// why the placeholder assertions below read the DOM synchronously right after
// render, before the event loop can deliver the error.
//
// ── HARNESS NOTE — why a `process` shim, and why it is honest here.
// The `components` vitest project is bare Vite in a real chromium: no Next
// plugin, so nothing defines the `process` global. next/image reads
// `process.env.__NEXT_IMAGE_OPTS` at MODULE scope (image-component.js:26), so
// importing the real ExportedImage throws "process is not defined" before a
// single test runs. vi.hoisted is the sanctioned pre-import seam (Vitest
// transforms static imports, so this really does execute first).
// Deliberately EMPTY env, not a copy of next.config.ts: with
// `__NEXT_IMAGE_OPTS` undefined next/image falls back to `imageConfigDefault`
// (get-img-props.js:151) and the optimizer's own reads fall back to their
// documented defaults (WebP on, `nextImageExportOptimizer` folder name) —
// i.e. the same shape the app ships, without this file pretending to be a
// second source of truth for the build config. The sanctioned repo-wide cure
// would be a define/setup entry in vitest.config.ts — outside this lane's
// write surface (same reasoning Header.test.tsx records for its mock
// boundary). Storybook's own runner needs none of this: @storybook/nextjs-vite
// supplies the Next environment, which is why the stories tier stays clean.
vi.hoisted(() => {
  if (!('process' in globalThis)) {
    Object.defineProperty(globalThis, 'process', {
      value: { env: {} },
      configurable: true,
      writable: true,
    });
  }
});

// Fixtures are the two committed demo assets, Romanian alts with diacritics
// (§15.7) and CMSR-factual (no superlatives, no promises).
// The alts live OUTSIDE the spread objects on purpose: eslint-config-next maps
// <Image> to img for jsx-a11y/alt-text, and a spread does not satisfy it — the
// alt has to be readable at the JSX call site. Exactly the right enforcement
// for this atom, so it is honoured rather than disabled.
const HERO = {
  src: 'images/demo/hero-calm.jpg',
  width: 1600,
  height: 1200,
};
const HERO_ALT = 'Cabinet stomatologic modern, luminos';

const CAT = {
  src: 'images/demo/transparent-artwork-cat.png',
  width: 847,
  height: 567,
};
// Carries ț ă ș î — a broken encoding path fails here, not in front of a
// patient. Also the artwork fixture: transparent PNG, the logo's stand-in
// until the Publio SVG lands (§15.6).
const CAT_ALT = 'Ilustrație demonstrativă: pisică pe fundal transparent';

// Record<ImageVariant, …> on purpose: a fourth variant cannot ship with zero
// coverage — this file stops typechecking until it is classified here.
// Byte-exact strings, not substrings: the recipe order is the §6.8 merge
// contract (atom classes first, caller className last), so `toBe` is the
// assertion, never `toContain`.
const VARIANT_CLASSES: Record<ImageVariant, string> = {
  // plain is byte-exact pass-through: the atom contributes NOTHING.
  plain: '',
  framed: 'h-full w-full rounded-xl object-cover',
  artwork: 'h-auto max-w-full object-contain',
};

const VARIANTS = Object.keys(VARIANT_CLASSES) as ImageVariant[];

const tokensOf = (element: Element) =>
  element.className.split(/\s+/).filter(Boolean);

describe('Image — the element and its accessible name (§9, D7)', () => {
  it('renders an <img> named by alt, diacritics intact (ț ă ș î)', () => {
    render(<Image {...CAT} alt={CAT_ALT} />);
    // Name-scoped role query: this is exactly what a screen reader announces,
    // and it fails if any layer mangles the Romanian characters.
    const image = screen.getByRole('img', { name: CAT_ALT });
    expect(image.tagName).toBe('IMG');
    expect(image).toHaveAttribute('alt', CAT_ALT);
  });

  it('keeps width/height on the element — reserved space, zero layout shift (§11)', () => {
    render(<Image {...HERO} alt={HERO_ALT} />);
    const image = screen.getByRole('img', { name: HERO_ALT });
    expect(image).toHaveAttribute('width', String(HERO.width));
    expect(image).toHaveAttribute('height', String(HERO.height));
  });

  it('alt="" renders a decorative image with NO img role (D7)', () => {
    // The a11y-correct marking for a purely visual image: assistive tech skips
    // it entirely (implicit role `presentation`). The atom must not fake a name
    // for it — an empty alt is a decision, not a missing string.
    const { container } = render(<Image {...CAT} alt="" variant="artwork" />);
    expect(screen.queryByRole('img')).not.toBeInTheDocument();
    const decorative = within(container).getByRole('presentation');
    expect(decorative.tagName).toBe('IMG');
    expect(decorative).toHaveAttribute('alt', '');
    // …and it still wears its variant recipe: decorative ≠ unstyled.
    expect(decorative.className).toBe(VARIANT_CLASSES.artwork);
  });
});

describe('Image — variant is the whole presentation axis (D1)', () => {
  it('defaults to plain and emits NO class attribute at all (pass-through purity)', () => {
    // The pinned invariant behind D5: a bare <Image> is byte-exactly the
    // 14-line pass-through this rework replaces, so the future Hero section
    // owns 100% of the geometry. An empty class="" would already be a class
    // the parent has to reason about.
    render(<Image {...HERO} alt={HERO_ALT} />);
    expect(screen.getByRole('img', { name: HERO_ALT })).not.toHaveAttribute(
      'class',
    );
  });

  it('renders variant="plain" identically to the bare call (D5 default pinned)', () => {
    // The default stays 'plain' FOREVER: union growth (the deferred overlay
    // mode) must never restyle an existing call site (§6.6 silent-break guard).
    const { unmount } = render(<Image {...HERO} alt={HERO_ALT} />);
    const bare = screen.getByRole('img', { name: HERO_ALT }).outerHTML;
    unmount();
    render(<Image {...HERO} alt={HERO_ALT} variant="plain" />);
    expect(screen.getByRole('img', { name: HERO_ALT }).outerHTML).toBe(bare);
  });

  it('framed fills its box, crops, and rounds at 12px (D2, fb-195)', () => {
    render(<Image {...HERO} alt={HERO_ALT} variant="framed" />);
    const image = screen.getByRole('img', { name: HERO_ALT });
    // h-full + w-full = obey the parent box; object-cover = cover it, crop the
    // overflow, never distort; rounded-xl = the fixed 12px radius, MORE than
    // the Header pill's 8px (owner "agree", fb-195). Radius is not a prop (D3).
    expect(tokensOf(image)).toEqual([
      'h-full',
      'w-full',
      'rounded-xl',
      'object-cover',
    ]);
    expect(image.className).toBe(VARIANT_CLASSES.framed);
  });

  it('artwork shows the whole image and never upscales it (D4)', () => {
    render(<Image {...CAT} alt={CAT_ALT} variant="artwork" />);
    const image = screen.getByRole('img', { name: CAT_ALT });
    // max-w-full shrinks below intrinsic size but never stretches a raster
    // past it (blurry logos banned by construction); object-contain
    // letterboxes instead of cropping when a parent constrains both axes.
    expect(tokensOf(image)).toEqual(['h-auto', 'max-w-full', 'object-contain']);
    expect(image.className).toBe(VARIANT_CLASSES.artwork);
  });

  it.each(VARIANTS)(
    'variant "%s" emits exactly its own class set and nothing else',
    (variant) => {
      render(<Image {...HERO} alt={HERO_ALT} variant={variant} />);
      expect(screen.getByRole('img', { name: HERO_ALT }).className).toBe(
        VARIANT_CLASSES[variant],
      );
    },
  );

  it.each(VARIANTS)(
    'variant "%s" owns no outer margin (§6.4 — the parent owns spacing)',
    (variant) => {
      render(<Image {...HERO} alt={HERO_ALT} variant={variant} />);
      const tokens = tokensOf(screen.getByRole('img', { name: HERO_ALT }));
      expect(tokens.filter((t) => /^-?m[trblxyse]?-/.test(t))).toEqual([]);
    },
  );

  it('never leaks `variant` onto the DOM element', () => {
    // React 19 forwards unknown props to the DOM verbatim, so a `variant` that
    // slipped through the spread would surface as variant="framed" right here.
    render(<Image {...HERO} alt={HERO_ALT} variant="framed" />);
    expect(screen.getByRole('img', { name: HERO_ALT })).not.toHaveAttribute(
      'variant',
    );
  });
});

describe('Image — §6.8 native-element fidelity', () => {
  it('plain + className renders exactly that className, nothing prepended', () => {
    // Pass-through purity again, from the caller's side: what the parent wrote
    // is what the element wears.
    render(<Image {...HERO} alt={HERO_ALT} className="absolute inset-0" />);
    expect(screen.getByRole('img', { name: HERO_ALT }).className).toBe(
      'absolute inset-0',
    );
  });

  it.each(VARIANTS)(
    'variant "%s" merges the caller className LAST (order is the contract)',
    (variant) => {
      // Order, not membership: the merge order is a deterministic CONVENTION
      // (§6.8) — attribute order never decides CSS conflicts, and caller
      // className is sanctioned for positioning/spacing only, never for
      // out-styling a variant's internals (G2 react MEDIUM).
      render(
        <Image
          {...HERO}
          alt={HERO_ALT}
          variant={variant}
          className="aspect-square"
        />,
      );
      expect(screen.getByRole('img', { name: HERO_ALT }).className).toBe(
        `${VARIANT_CLASSES[variant]} aspect-square`.trim(),
      );
    },
  );

  it('accepts ref as a regular prop (React 19) reaching the <img> node', () => {
    const ref = createRef<HTMLImageElement>();
    render(<Image {...HERO} alt={HERO_ALT} ref={ref} />);
    expect(ref.current).toBeInstanceOf(HTMLImageElement);
    expect(ref.current).toBe(screen.getByRole('img', { name: HERO_ALT }));
  });

  it('spreads remaining native props onto the rendered element', () => {
    render(
      <Image
        {...HERO}
        alt={HERO_ALT}
        variant="framed"
        sizes="(min-width: 768px) 50vw, 100vw"
        data-testid="doctor-photo"
        id="foto-medic"
      />,
    );
    const image = screen.getByTestId('doctor-photo');
    expect(image).toBe(screen.getByRole('img', { name: HERO_ALT }));
    expect(image).toHaveAttribute('sizes', '(min-width: 768px) 50vw, 100vw');
    expect(image).toHaveAttribute('id', 'foto-medic');
    // sizes is load-bearing, not decoration: it is what makes the browser pick
    // a right-sized file out of the srcset the optimizer bakes in (§11).
    // Pinned to the OPTIMIZED pipeline, not mere existence: the error-fallback
    // loader would also emit a srcset, but only the real one points into the
    // optimizer's folder — and synchronously after render the error event
    // cannot have fired yet (G2 react NIT).
    expect(image.getAttribute('srcset')).toContain('nextImageExportOptimizer');
  });

  it('leaves loading behaviour to the native props (preload → eager, §10.6)', () => {
    // `preload` is Next 16's name for the old `priority` (which survives only
    // as a deprecated alias mapped onto it — get-img-props.js: preload ||
    // priority). New code models the living name.
    const { container: lazyBox } = render(<Image {...HERO} alt={HERO_ALT} />);
    const { container: eagerBox } = render(
      <Image {...HERO} alt={HERO_ALT} preload />,
    );
    expect(within(lazyBox).getByRole('img')).toHaveAttribute('loading', 'lazy');
    expect(within(eagerBox).getByRole('img')).not.toHaveAttribute(
      'loading',
      'lazy',
    );
  });
});

describe('Image — placeholder policy (D4)', () => {
  // What is DOM-observable: ExportedImage paints its blur as an INLINE
  // background-image on the <img> (it has to — the generated blur is a URL,
  // not the base64 string next/image expects). So `style.backgroundImage`
  // is the honest signal for "a blur placeholder is in effect", and its
  // absence for "empty". Read synchronously right after render: the 404 on the
  // (ungenerated) optimized URL later flips the component into its fallback
  // and clears the blur, and that error can only be delivered at a macrotask
  // boundary — so no `await` may be introduced between render and assertion.
  const blurOf = (element: HTMLElement) => element.style.backgroundImage;

  it('artwork defaults to placeholder="empty" — no blur behind transparency', () => {
    // Differential proof on ONE fixture: the same transparent PNG blurs as
    // plain (the repo-wide default) and does not as artwork. Blur under
    // transparency would flash a smeared ghost rectangle where the logo's
    // ground should stay empty.
    const { container: plainBox } = render(<Image {...CAT} alt={CAT_ALT} />);
    const { container: artworkBox } = render(
      <Image {...CAT} alt={CAT_ALT} variant="artwork" />,
    );
    const blurred = blurOf(
      within(plainBox).getByRole('img', { name: CAT_ALT }),
    );
    const flat = blurOf(within(artworkBox).getByRole('img', { name: CAT_ALT }));

    expect(blurred).toContain('transparent-artwork-cat');
    expect(flat).toBe('');
  });

  it('an explicit placeholder prop always wins over the variant default', () => {
    // §6.8 native fidelity: the variant sets a DEFAULT, never a policy the
    // caller cannot leave. Both directions asserted — artwork can opt back IN
    // to blur, plain/framed can opt OUT.
    const { container: forcedBlur } = render(
      <Image {...CAT} alt={CAT_ALT} variant="artwork" placeholder="blur" />,
    );
    const { container: forcedEmpty } = render(
      <Image {...HERO} alt={HERO_ALT} placeholder="empty" />,
    );
    expect(
      blurOf(within(forcedBlur).getByRole('img', { name: CAT_ALT })),
    ).toContain('transparent-artwork-cat');
    expect(
      blurOf(within(forcedEmpty).getByRole('img', { name: HERO_ALT })),
    ).toBe('');
  });

  it('leaves plain and framed on the repo-wide blur default (untouched)', () => {
    const { container: plainBox } = render(<Image {...HERO} alt={HERO_ALT} />);
    const { container: framedBox } = render(
      <Image {...HERO} alt={HERO_ALT} variant="framed" />,
    );
    expect(blurOf(within(plainBox).getByRole('img'))).toContain('hero-calm');
    expect(blurOf(within(framedBox).getByRole('img'))).toContain('hero-calm');
  });
});
