// Generates out/index.html — the root "/" locale redirect stub (brief §5,
// re-amended 2026-09-06, owner — root Romanian-first: cookie → defaultLocale,
// nothing else) — FROM src/i18n/locales.ts and src/i18n/href.ts, so neither
// the locale list nor the URL shape can drift from the modules that own them.
// Runs as the last step of `npm run build` on plain Node (24+ strips types
// natively). Deterministic: same inputs ⇒ same bytes.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { localeHref } from '../src/i18n/href.ts';
import {
  defaultLocale,
  locales,
  LOCALE_COOKIE,
  nativeNames,
} from '../src/i18n/locales.ts';

const outDir = join(process.cwd(), 'out');
if (!existsSync(outDir)) {
  console.error(
    'out/ not found — run `next build` first (this runs inside `npm run build`).',
  );
  process.exit(1);
}

const messages = JSON.parse(
  readFileSync(
    join(process.cwd(), 'src', 'messages', `${defaultLocale}.json`),
    'utf8',
  ),
) as { common: { siteName: string } };

// Interim GitHub Pages serves under /<repo>/ (§15.2 amended 2026-08-02):
// PAGES_BASE_PATH prefixes every path; NOINDEX=1 (or STAGING=1) keeps the
// github.io copy out of Google until the real domain is attached. `base` is
// read here for the log line only — every URL in the page comes from localeHref
// (§15.13), including the script's.
const base = process.env.PAGES_BASE_PATH ?? '';
const noindex = process.env.NOINDEX === '1' || process.env.STAGING === '1';

// BOTH shapes come from the same builder (org review D12). The inline script
// cannot CALL it — it is emitted as text and runs in the visitor's browser,
// where no module of ours exists — so the call happens here, at build time, and
// what ships is its RESULT: a locale → href table the script only indexes into.
// The visitor's browser therefore performs no URL arithmetic of its own, and
// href.ts is left with no second spelling to stay in step with.
// The tuple annotation is load-bearing: without it the entries infer as
// string[][] and Object.fromEntries falls to its `any` overload.
const hrefs = Object.fromEntries(
  locales.map((l): [string, string] => [l, localeHref(l, '/')]),
);

// Each link is IN its own language ("Deutsch", « Français »), so it carries
// its own lang — SC 3.1.2: without it a screen reader pronounces "Deutsch"
// with the page's Romanian voice — and hreflang, the destination's language
// (same code both times).
const links = locales
  .map(
    (l) =>
      `      <li><a href="${hrefs[l]}" lang="${l}" hreflang="${l}">${nativeNames[l]}</a></li>`,
  )
  .join('\n');

// `LOCALE_COOKIE` is INTERPOLATED into the emitted cookie regex below, the same
// way `hrefs` is: this tool is the cookie's only READER and the switcher its
// only writer (see the constant's own note in src/i18n/locales.ts), so the name
// travels as one value instead of as two matching strings. Two consequences of
// it being EMITTED rather than called: the name must stay REGEX-SAFE — a
// metacharacter in it would silently change what the pattern matches, and no
// type can catch that — and any change to it moves the generated bytes, so the
// proof lives in a diff of out/index.html, never in a reading of this file.

// ── THE WALK THAT LEFT (owner, 2026-09-06 — root Romanian-first; supersedes
// D1/#67's no-match-→-/en). Until this date the script below also walked
// navigator.languages, held verdict-for-verdict against src/i18n/match.ts'
// matchLocale as a KEEP-IN-SYNC pair. The pair is dissolved by deletion, not
// extraction: the stub now asks ONE question — the §8.7 cookie the visitor set
// by explicit click — and otherwise lands on defaultLocale. Auto-detection
// lives in ONE place instead, the §8.6 suggestion banner
// (sections/LanguageBanner over matchLocale), which OFFERS the visitor's
// language on the page they landed on and never redirects (D3).
// THE ACCEPTED TRADE-OFF, recorded: a visitor whose browser speaks none of
// the five now gets Romanian and the language dial, not English — and for
// them the banner stays silent too (matchLocale returns null; nothing to
// suggest). Google traffic is unaffected either way: hreflang routes language
// searches before "/" is ever clicked, and the sitemap x-default was already
// /ro — the old /en-vs-/ro asymmetry dies here.
// tests/unit/locale-match.test.ts pins this contract: cookie-valid → its
// locale · anything else → defaultLocale · NO navigator reference in the
// emitted text.
// (This block sits OUTSIDE the `html` template on purpose: everything between
// the backticks is shipped bytes, and out/index.html is pinned by sha.)
const html = `<!doctype html>
<html lang="${defaultLocale}">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${messages.common.siteName}</title>${noindex ? '\n    <meta name="robots" content="noindex" />' : ''}
    <!--
      GENERATED by tools/generate-root-redirect.ts from src/i18n/locales.ts
      (the locales) and src/i18n/href.ts (every URL below) — do not edit by
      hand. Root "/" redirect (brief §5, re-amended 2026-09-06): cookie →
      /${defaultLocale}. The browser's language is not read here — the
      in-page suggestion banner is the only auto-detect surface (§8.6).
      lang="${defaultLocale}" above is unchanged on purpose: this stub's
      title and crawler link list stay the ${defaultLocale}-default page.
      The cookie is only ever SET elsewhere on explicit user click (§8.7);
      this script merely reads it. No IP/geolocation, ever (§8.6).
    -->
    <script>
      (function () {
        var hrefs = ${JSON.stringify(hrefs)};
        var locales = ${JSON.stringify([...locales])};
        var target = null;
        var m = document.cookie.match(/(?:^|;\\s*)${LOCALE_COOKIE}=([a-z]{2})/);
        if (m && locales.indexOf(m[1]) !== -1) target = m[1];
        location.replace(hrefs[target || '${defaultLocale}']);
      })();
    </script>
  </head>
  <body>
    <!-- Visible on purpose (not <noscript>): JS users are redirected before
         paint; no-JS users get real navigation; crawlers and the linkinator
         gate get a followable entry into every locale tree (§13). -->
    <ul>
${links}
    </ul>
  </body>
</html>
`;

writeFileSync(join(outDir, 'index.html'), html);
console.log(
  `out/index.html generated for [${locales.join(', ')}], default "${defaultLocale}", base "${base || '/'}", noindex=${noindex}.`,
);
