// Generates out/index.html — the root "/" locale redirect stub (brief §5:
// cookie → navigator.language → default) — FROM src/i18n/locales.ts, so the
// stub can never drift from the routing module. Runs as the last step of
// `npm run build` on plain Node (24+ strips types natively). Deterministic:
// same inputs ⇒ same bytes.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { defaultLocale, locales, nativeNames } from '../src/i18n/locales.ts';

const outDir = join(process.cwd(), 'out');
if (!existsSync(outDir)) {
  console.error(
    'out/ not found — run `next build` first (this runs inside `npm run build`).',
  );
  process.exit(1);
}

const messages = JSON.parse(
  readFileSync(
    join(process.cwd(), 'src', 'messages', `${defaultLocale}.json`),
    'utf8',
  ),
) as { common: { siteName: string } };

const links = locales
  .map((l) => `      <li><a href="/${l}/">${nativeNames[l]}</a></li>`)
  .join('\n');

const html = `<!doctype html>
<html lang="${defaultLocale}">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${messages.common.siteName}</title>
    <!--
      GENERATED by tools/generate-root-redirect.ts from src/i18n/locales.ts —
      do not edit by hand. Root "/" redirect (brief §5): cookie →
      navigator.language → /${defaultLocale}. The cookie is only ever SET
      elsewhere on explicit user click (§8.7); this script merely reads it.
      No IP/geolocation, ever (§8.6).
    -->
    <script>
      (function () {
        var locales = ${JSON.stringify([...locales])};
        var target = null;
        var m = document.cookie.match(/(?:^|;\\s*)NEXT_LOCALE=([a-z]{2})/);
        if (m && locales.indexOf(m[1]) !== -1) target = m[1];
        if (!target) {
          var prefs = navigator.languages || [navigator.language || ''];
          for (var i = 0; i < prefs.length && !target; i++) {
            var p = String(prefs[i]).slice(0, 2).toLowerCase();
            if (locales.indexOf(p) !== -1) target = p;
          }
        }
        location.replace('/' + (target || '${defaultLocale}') + '/');
      })();
    </script>
  </head>
  <body>
    <!-- Visible on purpose (not <noscript>): JS users are redirected before
         paint; no-JS users get real navigation; crawlers and the linkinator
         gate get a followable entry into every locale tree (§13). -->
    <ul>
${links}
    </ul>
  </body>
</html>
`;

writeFileSync(join(outDir, 'index.html'), html);
console.log(
  `out/index.html generated for [${locales.join(', ')}], default "${defaultLocale}".`,
);
